### ISSUE TITLE
Permissions wrong on /hostdir

### ISSUE THREAD

**Issue by the-maldridge** [the-maldridge/void-infrastructure#3]
/hostdir must be writable by the buildslave user and world readable for mirror access.

**Comment by the-maldridge** [comment]
hostdir needs to be writeable by the buildslaves and the repo management user.  See voidlinux/void-packages#5449 for tracking.

**Comment by Gottox** [comment]
We had similiar issues to /hostdir/sources. See: https://build.voidlinux.eu/builders/x86_64_builder/builds/53/steps/shell_3/logs/stdio

**Comment by the-maldridge** [comment]
Fixed.
