### ISSUE TITLE
xlocate.git no longer updating

### ISSUE THREAD

**Issue by ebfe** [the-maldridge/void-infrastructure#5]
Last update is from `Date:   Wed Feb 1 23:03:04 2017 +0100`

**Comment by ebfe** [comment]
Apprently these where updated once and are now stuck at `Date:   Sat Mar 18 21:26:57 2017 +0100`

**Comment by the-maldridge** [comment]
I'm 95% sure this is due to a permissions issue and the user that xlocate.git isn't in the right groups.  I won't have time to look at this until Friday night, but this is on my todo list.

**Comment by the-maldridge** [comment]
This is almost certainly related to #3 .

**Comment by the-maldridge** [comment]
This wound up being a permissions problem and has since been corrected.
